export const API_URL = 'https://api.icaromh.com'

export const GOOGLE_ANALYTICS_KEY = 'UA-50597564-8'


export const EVENT_CATEGORY_VIDEO = 'VIDEO'
export const EVENT_CATEGORY_SEARCH = 'SEARCH'
export const EVENT_CATEGORY_NAVIGATION = 'NAVIGATION'

// SEARCH ACTIONS
export const SEARCH_TERM = 'TERM'
export const SEARCH_FOCUS = 'FOCUS'

// VIDEO ACTIONS
export const VIDEO_READY = 'READY'
export const VIDEO_PLAY = 'PLAY'
export const VIDEO_PAUSE = 'PAUSE'
export const VIDEO_DOWNLOAD = 'DOWNLOAD'

// NAVIGATION ACTIONS
export const NAVIGATION_CLICK = 'CLICK'
export const NAVIGATION_HOME_CLICK = 'HOME CLICK'
export const NAVIGATION_FAVORITE_CLICK = 'FAVORITE CLICK'
export const NAVIGATION_SHOW_CLICK = 'SHOW CLICK'
export const NAVIGATION_SEASON_SELECT_CLICK = 'SEASON SELECT CLICK'
export const NAVIGATION_SEASON_CLICK = 'SEASON CLICK'
export const NAVIGATION_EPISODE_CLICK = 'EPISODE CLICK'


// PLAYER
export const REMAIN_TIME_TO_SHOW_NEXT_EPISODE = 60 // 15 seconds
